require "bundler/gem_tasks"
require "rake/testtask"
require "rdoc/task"

Rake::TestTask.new do |t|
	t.libs << 'test'
	t.pattern = "test/*_test.rb"
end

RDoc::Task.new do |t|
	t.rdoc_files.include("README.md", "lib/**/*rb")
end
